# Generated by Django 4.1 on 2022-12-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tile', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=80)),
                ('book_editor', models.CharField(max_length=80)),
                ('book_genre', models.CharField(max_length=30)),
                ('book_cover', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Book_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(verbose_name='date borrowed')),
                ('return_date', models.DateTimeField(verbose_name='date returned')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.library')),
            ],
        ),
    ]
