# Generated by Django 4.1 on 2022-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='library',
            name='department_code',
            field=models.IntegerField(default=75),
        ),
    ]
