# Generated by Django 4.1 on 2022-12-18 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_book_instance_library'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_instance',
            new_name='BookInstance',
        ),
    ]
