# Generated by Django 4.1 on 2022-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_book_tile_book_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='Bibliothèque sans nom', max_length=200),
        ),
    ]
