# Generated by Django 4.1 on 2022-12-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_library_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_editor',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='name',
        ),
    ]
