# Generated by Django 4.1 on 2022-12-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrow_date',
            field=models.DateField(blank=True, null=True, verbose_name='date borrowed'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='date returned'),
        ),
    ]
