# Generated by Django 4.1 on 2022-12-28 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_lecturegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturegroup',
            name='date',
        ),
        migrations.AddField(
            model_name='lecturegroup',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 18, 21, 18, 981002), verbose_name='start date time of the meeting'),
        ),
        migrations.AddField(
            model_name='lecturegroup',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 17, 21, 18, 980992), verbose_name='start date time of the meeting'),
        ),
    ]
