# Generated by Django 4.1 on 2022-12-28 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_remove_lecturegroup_date_lecturegroup_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturegroup',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 22, 32, 33, 581336), verbose_name='start date time of the meeting'),
        ),
        migrations.AlterField(
            model_name='lecturegroup',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 21, 32, 33, 581317), verbose_name='start date time of the meeting'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creationDateTime', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 21, 32, 33, 582418), verbose_name='date of creation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]